<?php
/**
 * Exception codes for newsfeed system.
 *
 * @copyright &copy; 2006 The Open University
 * @author s.marshall@open.ac.uk
 * @license http://www.gnu.org/copyleft/gpl.html GNU Public License
 * @package newsfeed
 *//** */
define('EXN_NEWSFEED_BASE',                 10400);

define('EXN_NEWSFEED_LOCATIONINVALID',      EXN_NEWSFEED_BASE+1);
define('EXN_NEWSFEED_NAMEINVALID',          EXN_NEWSFEED_BASE+2);
define('EXN_NEWSFEED_PRESINVALID',          EXN_NEWSFEED_BASE+3);
define('EXN_NEWSFEED_DATEINVALID',          EXN_NEWSFEED_BASE+4);
define('EXN_NEWSFEED_URLINVALID',           EXN_NEWSFEED_BASE+5);
define('EXN_NEWSFEED_SUMMARYINVALID',       EXN_NEWSFEED_BASE+6);
define('EXN_NEWSFEED_PUBLICINVALID',        EXN_NEWSFEED_BASE+7);
define('EXN_NEWSFEED_AUTHIDINVALID',        EXN_NEWSFEED_BASE+8);
define('EXN_NEWSFEED_TITLEINVALID',         EXN_NEWSFEED_BASE+9);
define('EXN_NEWSFEED_HTMLINVALID',          EXN_NEWSFEED_BASE+10);
define('EXN_NEWSFEED_USERINVALID',          EXN_NEWSFEED_BASE+11);
define('EXN_NEWSFEED_FILENAMEINVALID',      EXN_NEWSFEED_BASE+12);
define('EXN_NEWSFEED_MIMETYPEINVALID',      EXN_NEWSFEED_BASE+13);
define('EXN_NEWSFEED_SIZEINVALID',          EXN_NEWSFEED_BASE+14);
define('EXN_NEWSFEED_DELETEDINVALID',       EXN_NEWSFEED_BASE+15);
define('EXN_NEWSFEED_FOLDERINVALID',        EXN_NEWSFEED_BASE+16);
define('EXN_NEWSFEED_ROLLFORWARDINVALID',   EXN_NEWSFEED_BASE+17);
define('EXN_NEWSFEED_FREQINVALID',          EXN_NEWSFEED_BASE+18);
define('EXN_NEWSFEED_ERRORINVALID',         EXN_NEWSFEED_BASE+19);
// Out of constants in this range! Continued below

define('EXN_NEWSFEED_NOID',                 EXN_NEWSFEED_BASE+20);
define('EXN_NEWSFEED_GOTID',                EXN_NEWSFEED_BASE+21);
define('EXN_NEWSFEED_INVALIDID',            EXN_NEWSFEED_BASE+22);
define('EXN_NEWSFEED_INVALIDPARAMS',        EXN_NEWSFEED_BASE+23);
define('EXN_NEWSFEED_ROLENOTSET',           EXN_NEWSFEED_BASE+24);
define('EXN_NEWSFEED_BLOCKINSTANCEINVALID', EXN_NEWSFEED_BASE+25);

define('EXN_NEWSFEED_LINKINVALID',          EXN_NEWSFEED_BASE+29);

define('EXN_NEWSFEED_UNKNOWNFIELD',         EXN_NEWSFEED_BASE+30);
define('EXN_NEWSFEED_UNKNOWNTYPE',          EXN_NEWSFEED_BASE+31);
define('EXN_NEWSFEED_ENTRYNOTFOUND',        EXN_NEWSFEED_BASE+32);

define('EXN_NEWSFEED_ALREADYGOTROLE',       EXN_NEWSFEED_BASE+40);
define('EXN_NEWSFEED_NOTGOTROLE',           EXN_NEWSFEED_BASE+41);
define('EXN_NEWSFEED_ALREADYGOTAUTHID',     EXN_NEWSFEED_BASE+42);
define('EXN_NEWSFEED_NOTGOTAUTHID',         EXN_NEWSFEED_BASE+43);

define('EXN_NEWSFEED_CHANGEDAPPROVE',       EXN_NEWSFEED_BASE+50);
define('EXN_NEWSFEED_NONEWSFEED',           EXN_NEWSFEED_BASE+51);
define('EXN_NEWSFEED_NOTNEWENTRY',          EXN_NEWSFEED_BASE+52);
define('EXN_NEWSFEED_NOENTRY',              EXN_NEWSFEED_BASE+53);
define('EXN_NEWSFEED_NOSUCHFILE',           EXN_NEWSFEED_BASE+54);
define('EXN_NEWSFEED_NOSTARTDATE',          EXN_NEWSFEED_BASE+55);
define('EXN_NEWSFEED_NOFILENAME',           EXN_NEWSFEED_BASE+56);
define('EXN_NEWSFEED_ATTACHMENTIOERROR',    EXN_NEWSFEED_BASE+57);
define('EXN_NEWSFEED_NOTFROMDB',            EXN_NEWSFEED_BASE+58);

define('EXN_NEWSFEED_FEEDFORMATERROR',      EXN_NEWSFEED_BASE+60);
define('EXN_NEWSFEED_FEEDNOTPUBLIC',        EXN_NEWSFEED_BASE+61);
define('EXN_NEWSFEED_BUILDERRORIO',         EXN_NEWSFEED_BASE+62);

define('EXN_NEWSFEED_EMAILBADUSER',         EXN_NEWSFEED_BASE+70);
define('EXN_NEWSFEED_EMAILFAIL',            EXN_NEWSFEED_BASE+71);

?>